### ISSUE TITLE
Logo & CSS Images Not Showing in Inherited Theme

### ISSUE THREAD

**Issue by 01Kuzma** [pmoreno-rodriguez/grav-theme-delivernext#5]
Hello,
Using Grav 1.8 beta4 with delivernext theme (v1.1.1). 
Created inherited theme my-delivery-override using Grav’s built-in script (bin/plugin devtools new-theme) to customize templates but keep logo and add custom CSS, images and other settings which were set in the theme.

Setup:

    my-delivery-override: Inheritance via user/themes/my-delivery-override/my-delivery-override.yaml:
    streams:
    schemes:
    theme:
    type: ReadOnlyStream
    prefixes:
    ‘’:
    - ‘user://themes/my-delivery-override’
    - ‘user://themes/delivernext’

    Custom CSS: user/themes/my-delivery-override/assets/css/custom.css with background: url(‘/images/languages/code.png’) (image in user/images/languages/).

Issues:

   Logo: Disappears in my-delivery-override. Probably other assets too, but have not tested more. Copied logo settings to `user/config/themes/my-delivery-override.yaml` and image to `user/themes/my-delivery-override/images/`, no luck.
   CSS Images: Background images don’t load. Firefox console errors:
   Security Error: `Content at https://grav-2025.test/` may not load `moz-extension://b26acb47-90de-481e-89f2-c9dda63befd7/images/languages/code.png`
   while this does work in old Grav 1.7 overridden theme

Tried:

    Copied configs, blueprints, images.
    Cleared cache (bin/grav cache).

Questions:

   Why doesn’t my-delivery-override inherit logo settings? Or it relates to Grav itself?
   How to fix it properly?
   Can’t remember exactly, but maybe, a few years ago, I had the same problem with other templates…

Or is this a Grav 1.8 beta4 bug? Help appreciated!

**Comment by pmoreno-rodriguez** [comment]
Hi @01Kuzma . Have you tried duplicating the delivernext.yaml file from /user/config/themes to delivernext-child.yaml (or the name of your child theme?). For child themes, you also need the corresponding .yaml file in that folder, and you'll need to create it manually.
This works perfectly for me.

**Comment by pmoreno-rodriguez** [comment]
See the demo [delivernext.yaml](_demo/config/themes/delivernext.yaml ) and copy into your child yaml

**Comment by 01Kuzma** [comment]
Thank you for the tip.
I've copied preconfigured data from `user\config\themes\delivernext.yaml`

```
streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
         - 'user://themes/my-delivery-override'
         - 'user://themes/delivernext'
enabled: true
dropdown:
  enabled: false
sticky_menu:
  enabled: false
production-mode: false
back_to_top_button:
  enabled: true
custom_css: '0'
custom_js: '0'
theme_logo_enabled: true
type_logo_header: image
  ...
```

But basically, should the template inheritance process maintain this automatically?
Or it's by Grav core design?
